services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 150M
        reservations:
          cpus: '0.25'
          memory: 100M
    ports:
      - target: 80
        published: 80
        protocol: tcp
        host_ip: 0.0.0.0
      - target: 443
        published: 443
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: dka-panel-nginx-data
        target: /data
      - type: volume
        source: dka-panel-nginx-letsencrypt
        target: /etc/letsencrypt
    restart: always
    networks:
      - dka-web-server

volumes:
  dka-panel-nginx-data:
    driver: local
  dka-panel-nginx-letsencrypt:
    driver: local

networks:
  dka-web-server:
    external: true
