name: dev-dka-server

services:

  dka-parking-mongodb:
    image: mongo:4.4.18
    container_name: dev-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: Cyberhack2010
    ports:
      - "27017:27017"
    command: --storageEngine wiredTiger
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    volumes:
      - mongodb-data:/data/db
    networks:
      dka-parking-network:
        ipv4_address: 102.111.0.4


  dka-mariadb:
    image: mariadb:latest
    container_name: dka-mariadb
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    environment:
      MYSQL_ROOT_PASSWORD: Cyberhack2010
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      dka-parking-network:
  ipv4_address: 102.111.0.5

  dka-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dka-phpmyadmin
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 200M
        reservations:
          cpus: '0.15'
          memory: 100M
    environment:
      PMA_HOST: dka-mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: @Cyberhack2010
    ports:
      - "64333:80"
    networks:
      dka-parking-network:
        ipv4_address: 102.111.0.6

volumes:
  mongodb-data:
    name: dka-parking-mongodb
    driver: local
  mariadb-data:
    name: dka-parking-mariadb
    driver: local
networks:
  dka-parking-network:
    driver: bridge
    ipam:
      config:
        - subnet: 102.111.0.0/24