#!/bin/bash
set -e

export GZIP=-9
export DKA_MONGO_USERNAME=${DKA_MONGO_USERNAME:-root}
export DKA_MONGO_PASSWORD=${DKA_MONGO_PASSWORD:-123456789}
export DKA_HOSTNAME=$(hostname) # Ambil hostname sistem

# Konfigurasi
BACKUP_DIR="/backup"  # Direktori tujuan backup
TIMESTAMP=$(date +"%H-%M-%S_%d-%m-%Y")
ARCHIVE_FILE="${DKA_HOSTNAME}_${TIMESTAMP}.gz"  # Nama file arsip

# Membuat direktori backup jika belum ada
mkdir -p "$BACKUP_DIR"

# Melakukan backup MongoDB menggunakan mongodump
echo "Processing Backup MongoDB..."
if mongodump --host 127.0.0.1 --username "$DKA_MONGO_USERNAME" --password "$DKA_MONGO_PASSWORD" --verbose --gzip --archive="$BACKUP_DIR/$ARCHIVE_FILE"; then
    echo "Backup saved in $ARCHIVE_FILE"
else
    echo "Backup failed!" >&2
    exit 1
fi