name: dka-dev


services:
  mongo:
    image: yovanggaanandhika/mongo:13-slim-mongo-8.0.5
    container_name: dka-dev-mongo
    hostname: dka-dev-mongo
    restart: always
    environment:
      DKA_MONGO_PASSWORD: 123456789
      DKA_REPL_ENABLED: true
      DKA_CRON_ENABLE: true
      DKA_CRON_PRIODIC: "0 3 * * *"
      # S3 / Wasabi configurations
      DKA_S3_UPLOAD_ENABLE: true
      DKA_S3_BUCKET: my-wasabi-bucket
      DKA_S3_PATH: backups/mongodb
      DKA_S3_ENDPOINT: https://s3.ap-southeast-1.wasabisys.com
      DKA_S3_REGION: ap-southeast-1
      AWS_ACCESS_KEY_ID: your_access_key
      AWS_SECRET_ACCESS_KEY: your_secret_key
      # Auto maintenance
      DKA_MAINTENANCE_ENABLE: true
      DKA_MAINTENANCE_CRON: "0 4 * * *"
      DKA_MAINTENANCE_LOG: /var/log/mongodb/maintenance.log
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: data
        target: /data/db
      - type: volume
        source: backup
        target: /backup
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '1.0'
        reservations:
          memory: 250M
          cpus: '0.8'
    networks:
      - default

volumes:
  data:
    name : dka-dev-mongo-data
    external: true

  backup:
    name: dka-dev-mongo-backup
    external: true

networks:
  default:
    name: dka-dev
    external: true


