name: dka-database-mariadb-galera

services:

  mariadb-node1:
    image: yovanggaanandhika/mariadb:latest
    container_name: dka-mariadb-node1
    hostname: dka-mariadb-node1
    restart: always
    environment:
      DKA_ROOT_PASSWORD: Cyberhack2010
      DKA_DB_NAME: test
      DKA_DB_USERNAME: test
      DKA_DB_PASSWORD: Cyberhack2010
      
      # Galera Settings
      DKA_REPLICATION_MODE: galera
      DKA_GALERA_BOOTSTRAP: true
      DKA_GALERA_CLUSTER_NAME: dka_mariadb_cluster
      DKA_GALERA_CLUSTER_ADDRESS: gcomm://dka-mariadb-node1,dka-mariadb-node2
      
      DKA_CRON_ENABLE: false
      DKA_MAINTENANCE_ENABLE: false
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: data-node1
        target: /var/lib/mysql
    networks:
      - default

  mariadb-node2:
    image: yovanggaanandhika/mariadb:latest
    container_name: dka-mariadb-node2
    hostname: dka-mariadb-node2
    restart: always
    environment:
      DKA_ROOT_PASSWORD: Cyberhack2010
      DKA_DB_NAME: test
      DKA_DB_USERNAME: test
      DKA_DB_PASSWORD: Cyberhack2010
      
      # Galera Settings
      DKA_REPLICATION_MODE: galera
      DKA_GALERA_BOOTSTRAP: false
      DKA_GALERA_CLUSTER_NAME: dka_mariadb_cluster
      DKA_GALERA_CLUSTER_ADDRESS: gcomm://dka-mariadb-node1,dka-mariadb-node2
      
      DKA_CRON_ENABLE: false
      DKA_MAINTENANCE_ENABLE: false
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: data-node2
        target: /var/lib/mysql
    networks:
      - default

volumes:
  data-node1:
    driver: local
  data-node2:
    driver: local

networks:
  default:
    driver: bridge
