name: dka-goparking-tuza-mtos

services:
  backend:
    image: node:alpine
    container_name: mtos-backend
    hostname: mtos-backend
    depends_on:
      - database
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 200M
    environment:
      DKA_SERVER_HOST: 0.0.0.0
      DKA_SERVER_PORT: 2118
      DKA_DATABASE_HOST: mtos-database
      DKA_DATABASE_USER: madinah
      DKA_DATABASE_PASSWORD: tuza88
      DKA_DATABASE_NAME: dka_mtos
      NODE_ENV: production
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - target: 2118
        published: 2118
        host_ip: 0.0.0.0
        protocol: tcp
    command: node src/index.js
    networks:
      - mtos-network

  database:
    image: yovanggaanandhika/mariadb:latest
    container_name: mtos-database
    hostname: mtos-database
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    environment:
      DKA_ROOT_PASSWORD: Cyberhack2010
      DKA_DB_NAME: dka_mtos
      DKA_DB_USERNAME: madinah
      DKA_DB_PASSWORD: tuza88
      DKA_CRON_ENABLE: true
      DKA_CRON_PRIODIC: 0 */6 * * *
    volumes:
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
      - type: bind
        source: ./backup
        target: /backup
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    networks:
      - mtos-network
      - dka-db-server

  bot:
    image: node:alpine
    container_name: mtos-bot
    hostname: mtos-bot
    depends_on:
      - database
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    environment:
      DKA_TELEGRAM_TOKEN: 7186848003:AAFBjp5C0WmTCFXy_jbuaKiAYRmE3c82rtE
      DKA_DATABASE_HOST: mtos-database
      DKA_DATABASE_USER: root
      DKA_DATABASE_PASSWORD: Cyberhack2010
      DKA_DATABASE_NAME: dka_mtos
      NODE_ENV: production
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: node src/bot/index.js
    networks:
      - mtos-network

volumes:
  mariadb-data:
    driver: local

networks:
  mtos-network:
    driver: bridge
  dka-db-server:
    external: true