ALTER USER postgres WITH ENCRYPTED PASSWORD '{{ROOT_PASSWORD}}';
CREATE USER {{DB_USERNAME}} WITH ENCRYPTED PASSWORD '{{DB_PASSWORD}}';
CREATE DATABASE {{DB_NAME}};
GRANT ALL PRIVILEGES ON DATABASE {{DB_NAME}} TO {{DB_USERNAME}};