-- --
CREATE DATABASE IF NOT EXISTS '{{DB_NAME}}';
CREATE USER IF NOT EXISTS '{{DB_USERNAME}}'@'%' IDENTIFIED BY '{{DB_PASSWORD}}';
GRANT ALL PRIVILEGES ON '{{DB_NAME}}'.* TO '{{DB_USERNAME}}'@'%';
CREATE USER 'root'@'%' IDENTIFIED BY '{{ROOT_PASSWORD}}';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;