#!/bin/bash

# Set database credentials
DB_USER="root"
# Set default values if environment variables are not provided
ROOT_PASSWORD=${DKA_ROOT_PASSWORD:-root}
BACKUP_DIR="/backup"
DATE=$(date +\%d-\%m-\%Y_\%H-\%M-\%S)
BACKUP_FILE="$BACKUP_DIR/schedule_backup_all_databases_$DATE.sql.gz"

# Create a backup directory if it doesn't exist
mkdir -p $BACKUP_DIR

echo "Backing up all databases..."

# Create a backup of all databases and compress it into a .sql.gz file using mariadb tools
ESCAPED_ROOT_PASSWORD=$(printf '%s' "$ROOT_PASSWORD" | sed 's/[&/]/\\&/g')
mariadb-dump -u $DB_USER -p"$ESCAPED_ROOT_PASSWORD" --all-databases --add-drop-table --routines --triggers --events --verbose --force | gzip -9 > "$BACKUP_FILE"

if [ $? -eq 0 ]; then
    echo "Backup completed successfully: $BACKUP_FILE"
else
    echo "Backup failed."
fi
