name: dev-dka-server
services:

  dka-nginx:
    image: nginx:latest
    container_name: dev-nginx
    restart: always
    links:
      - dka-mariadb
      - dka-mongodb
      - dka-postgresql
      - dka-redis
    ports:
      - target: 80
        published: 80
        host_ip: 0.0.0.0
      - target: 443
        published: 443
        host_ip: 0.0.0.0
    volumes:
      - type: bind
        source: ./config/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./www
        target: /var/www/html
    depends_on:
      - dka-php
      - dka-mariadb
      - dka-node
      - dka-postgresql
      - dka-redis
      - dka-mongodb
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.2

  dka-php:
    image: php:8.2-fpm
    container_name: dev-php8.2
    restart: always
    links:
      - dka-mariadb
      - dka-mongodb
      - dka-postgresql
      - dka-redis
    volumes:
      - type: bind
        source: ./www
        target: /var/www/html
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.3
    depends_on:
      - dka-mariadb

  dka-node:
    image: node:latest
    container_name: dev-node
    #user: node
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./app
        target: /home/node/app
    links:
      - dka-mariadb
      - dka-mongodb
      - dka-postgresql
      - dka-redis
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.4
    ports:
      - target: 3000
        published: 3000
        host_ip: 0.0.0.0
        protocol: tcp
    command: sh -c "yarn install && yarn run dev"
    depends_on:
      - dka-mongodb
      - dka-mariadb
      - dka-postgresql

  dka-mariadb:
    image: mariadb:latest
    container_name: dev-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cyberhack2010
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    ports:
      - target: 3306
        published: 3306
        host_ip: 0.0.0.0
        protocol: tcp
    volumes:
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.5

  dka-mongodb:
    image: mongo:latest
    container_name: dev-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: Cyberhack2010
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.6

  dka-postgresql:
    image: postgres:latest
    container_name: dev-postgresql
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Cyberhack2010
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.7

  dka-redis:
    image: redis:latest
    container_name: dev-redis
    restart: always
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        host_ip: 0.0.0.0
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.8

  dka-phpmyadmin:
    image: phpmyadmin
    container_name: dev-phpmyadmin
    restart: always
    environment:
      PMA_HOST: dka-mariadb
      MYSQL_ROOT_PASSWORD: Cyberhack2010
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    ports:
      - target: 80
        published: 8082
        host_ip: 0.0.0.0
        protocol: tcp
    depends_on:
      - dka-mariadb
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.9


  dka-mongo-express:
    image: mongo-express
    container_name: dev-mongo-express
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        host_ip: 0.0.0.0
    environment:
      ME_CONFIG_MONGODB_SERVER: dka-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: developer
      ME_CONFIG_MONGODB_ADMINPASSWORD: Cyberhack2010
    links:
      - dka-mongodb
    depends_on:
      - dka-mongodb
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.10

  dka-chrony:
    image: publicarray/chrony:latest
    container_name: dev-chrony
    restart: unless-stopped
    ports:
      - 123:123/udp
    volumes:
      - type: bind
        source: ./config/chrony/chrony.conf
        target: /etc/chrony.conf
        read_only: true
    cap_add:
      - SYS_TIME
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.11

  dka-emqx:
    image: emqx/emqx:latest
    container_name: dev-emqx
    restart: always
    ports:
      # MQTT port
      - target: 1883
        published: 1883
        host_ip: 0.0.0.0
      # WebSocket/HTTP port
      - target: 8080
        published: 8080
        host_ip: 0.0.0.0
      # Dashboard port
      - target: 18083
        published: 18083
        host_ip: 0.0.0.0
      # Secure MQTT port
      - target: 8883
        published: 8883
        host_ip: 0.0.0.0
      - target: 8083
        published: 8083
        host_ip: 0.0.0.0
    environment:
      EMQX_NAME: emqx
      EMQX_HOST: node1.emqx.io
      EMQX_NODE__NAME: node@127.0.0.1
      EMQX_NODE__COOKIE: Cyberhack2010
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_dashboard,emqx_auth_clientid,emqx_auth_username,emqx_auth_http"
    volumes:
      - type: volume
        source: emqx-data
        target: /opt/emqx/data
    networks:
      dka-development-server:
        ipv4_address: 102.113.0.12

volumes:
  mariadb-data:
    driver: local
  mongodb-data:
    driver: local
  postgresql-data:
    driver: local
  emqx-data:
    driver: local

networks:
  dka-development-server:
    driver: bridge
    ipam:
      config:
        - subnet: 102.113.0.0/24
