name: dev-dka-server

services:
  dka-nginx:
    image: nginx:latest
    container_name: dev-nginx
    restart: always
    links:
      - dka-mariadb
      - dka-mongodb
      - dka-postgresql
      - dka-redis
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html
    depends_on:
      - dka-php
      - dka-mariadb
      - dka-node
      - dka-postgresql
      - dka-redis
      - dka-mongodb
    networks:
      dka-web-network:
        ipv4_address: 102.113.0.2

  dka-php:
    build:
      dockerfile: context/dockerFile
    container_name: dev-php8.2
    hostname: dka-server-php1
    restart: always
    links:
      - dka-mariadb
      - dka-mongodb
      - dka-postgresql
      - dka-redis
    volumes:
      - ./www:/var/www/html
    networks:
      dka-web-network:
        ipv4_address: 102.113.0.3
    depends_on:
      - dka-mariadb

  dka-node:
    image: node:latest
    container_name: dev-node
    user: node
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./app:/home/node/app
    links:
      - dka-mariadb
      - dka-mongodb
      - dka-postgresql
      - dka-redis
    networks:
      dka-web-network:
        ipv4_address: 102.113.0.4
    ports:
      - "3000:3000"
    command: "yarn run dev"
    depends_on:
      - dka-mongodb
      - dka-mariadb
      - dka-postgresql

  dka-mariadb:
    image: mariadb:latest
    container_name: dev-mariadb
    hostname: dka-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cyberhack2010
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      dka-web-network:
        ipv4_address: 102.113.0.5

  dka-phpmyadmin :
    image: phpmyadmin/phpmyadmin
    container_name: dev-phpmyadmin
    hostname: dka-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    links:
      - dka-mariadb
    environment:
      PMA_HOST: dka-mariadb
      MYSQL_ROOT_PASSWORD: Cyberhack2010
    depends_on:
      - dka-mariadb
    networks:
      dka-web-network:
        ipv4_address: 102.113.0.6
    volumes:
      - type: volume
        source: phpmyadmin-data
        target: /etc/phpmyadmin

  dka-mongodb:
    image: mongo:latest
    container_name: dev-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: Cyberhack2010
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      dka-web-network:
        ipv4_address: 102.113.0.7

  dka-postgresql:
    image: postgres:latest
    container_name: dev-postgresql
    restart: always
    environment:
      #POSTGRES_DB: mydb
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Cyberhack2010
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      dka-web-network:
        ipv4_address: 102.113.0.8

  dka-redis:
    image: redis:latest
    container_name: dev-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      dka-web-network:
        ipv4_address: 102.113.0.9

volumes:
  nginx-config:
    driver: local
  mariadb-data:
    driver: local
  mongodb-data:
    driver: local
  postgresql-data:
    driver: local
  phpmyadmin-data:
    driver: local

networks:
  dka-web-network:
    driver: bridge
    ipam:
      config:
        - subnet: 102.113.0.0/24
