name: dka-database-postgresql-ms

services:

  postgresql-master:
    image: yovanggaanandhika/postgresql:17.0
    container_name: dka-postgresql-master
    hostname: dka-postgresql-master
    restart: always
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        host_ip: 0.0.0.0
    environment:
      # Replication Settings (Master)
      DKA_REPLICATION_MODE: master
      DKA_REPLICATION_USER: replicator
      DKA_REPLICATION_PASSWORD: replicator_pass
      
      # PostgreSQL default account configuration
      DKA_ROOT_USERNAME: postgres
      DKA_ROOT_PASSWORD: postgres
      DKA_DB_NAME: test
      DKA_DB_USERNAME: test
      DKA_DB_PASSWORD: test
      DKA_DB_MAX_CONNECTION: 200
      
      # Cron & Maintenance
      DKA_CRON_ENABLE: true
      DKA_MAINTENANCE_ENABLE: true
    volumes:
      - type: volume
        source: data-master
        target: /var/lib/postgresql
      - type: volume
        source: backup-master
        target: /backup
    networks:
      - default

  postgresql-slave:
    image: yovanggaanandhika/postgresql:17.0
    container_name: dka-postgresql-slave
    hostname: dka-postgresql-slave
    restart: always
    ports:
      - target: 5432
        published: 5433  # Port 5433 untuk Slave
        protocol: tcp
        host_ip: 0.0.0.0
    environment:
      # Replication Settings (Slave)
      DKA_REPLICATION_MODE: slave
      DKA_PEER_HOST: postgresql-master
      DKA_REPLICATION_USER: replicator
      DKA_REPLICATION_PASSWORD: replicator_pass
      
      # Konfigurasi disamakan persis dengan Master
      DKA_ROOT_USERNAME: postgres
      DKA_ROOT_PASSWORD: postgres
      DKA_DB_NAME: test
      DKA_DB_USERNAME: test
      DKA_DB_PASSWORD: test
      DKA_DB_MAX_CONNECTION: 200
      
      # Cron & Maintenance
      DKA_CRON_ENABLE: true
      DKA_MAINTENANCE_ENABLE: true
    volumes:
      - type: volume
        source: data-slave
        target: /var/lib/postgresql
      - type: volume
        source: backup-slave
        target: /backup
    networks:
      - default

volumes:
  data-master:
    driver: local
  backup-master:
    driver: local
  data-slave:
    driver: local
  backup-slave:
    driver: local

networks:
  default:
    driver: bridge
