version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Cyberhack2010
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        host_ip: 0.0.0.0
    restart: always
    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

volumes:
  mariadb_data:
    driver: local
