name: dka-hosting-inetnews

services:
  inetnews-app:
    image: wordpress:php8.2
    container_name: inetnews-app
    environment:
      WORDPRESS_DB_HOST: inetnews-mariadb
      WORDPRESS_DB_NAME: inetnews
      WORDPRESS_DB_USER: developer
      WORDPRESS_DB_PASSWORD: Cyberhack2010
    restart: always
    depends_on:
      - inetnews-mariadb
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    networks:
      - dka-web-server
      - inetnews-network

  inetnews-mariadb:
    image: mariadb:latest
    container_name: inetnews-mariadb
    hostname: inetnews-mariadb
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: developer
      MYSQL_ROOT_PASSWORD: Cyberhack2010
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    volumes:
      - type: bind
        source: ./sys_inetnews.sql
        target: /backup/sys_inetnews.sql
      - type: volume
        source: inetnews-db-data
        target: /var/lib/mysql
    networks:
      - inetnews-network
      - dka-db-server

volumes:
  inetnews-db-data:
    driver: local

networks:
  inetnews-network:
    driver: bridge

  dka-web-server:
    external: true

  dka-db-server:
    external: true