name: dka-hosting-tolibersatu

services:
  tolibersatu-app:
    image: wordpress:php8.2
    container_name: tolibersatu-app
    environment:
      WORDPRESS_DB_HOST: tolibersatu-mariadb
      WORDPRESS_DB_NAME: tolibersatu
      WORDPRESS_DB_USER: developer
      WORDPRESS_DB_PASSWORD: Cyberhack2010
    restart: always
    depends_on:
      - tolibersatu-mariadb
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    networks:
      - dka-web-server
      - tolibersatu-network

  tolibersatu-mariadb:
    image: mariadb:latest
    container_name: tolibersatu-mariadb
    hostname: tolibersatu-mariadb
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: developer
      MYSQL_ROOT_PASSWORD: Cyberhack2010
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    volumes:
      - type: bind
        source: ./sys_tolibersatu.sql
        target: /backup/sys_tolibersatu.sql
      - type: volume
        source: tolibersatu-db-data
        target: /var/lib/mysql
    networks:
      - tolibersatu-network
      - dka-db-server

volumes:
  tolibersatu-db-data:
    driver: local

networks:
  tolibersatu-network:
    driver: bridge

  dka-web-server:
    external: true

  dka-db-server:
    external: true