services:
  dka-mongo1:
    image: mongo:7
    container_name: dka-mongodb-cluster0
    hostname: dka-mongo1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: Cyberhack2010
      MONGO_REPLICA_SET_NAME: dkaReplicaSet
    ports:
      - "27017:27017"
    volumes:
      - mongodb1_data:/data/db
      - ./mongo-keyfile:/data/configdb/keyfile
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    command: [
      "mongod",
      "--replSet", "dkaReplicaSet",
      "--keyFile", "/data/configdb/keyfile",
      "--port",
      "27017",
      "--bind_ip_all"
    ]
    networks:
      mongo-net:
        ipv4_address: 103.113.1.2

  dka-mongo2:
    image: mongo:7
    container_name: dka-mongodb-cluster1
    hostname: dka-mongo2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: Cyberhack2010
      MONGO_REPLICA_SET_NAME: dkaReplicaSet
    volumes:
      - mongodb2_data:/data/db
      - ./mongo-keyfile:/data/configdb/keyfile
    ports:
      - "27018:27018"
    command: [
      "mongod",
      "--replSet", "dkaReplicaSet",
      "--keyFile", "/data/configdb/keyfile",
      "--port",
      "27018",
      "--bind_ip_all"
    ]
    networks:
      mongo-net:
        ipv4_address: 103.113.1.3

  dka-mongo3:
    image: mongo:7
    container_name: dka-mongodb-cluster2
    hostname: dka-mongo3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: Cyberhack2010
      MONGO_REPLICA_SET_NAME: dkaReplicaSet
    volumes:
      - mongodb3_data:/data/db
      - ./mongo-keyfile:/data/configdb/keyfile
    ports:
      - "27019:27019"
    networks:
      mongo-net:
        ipv4_address: 103.113.1.4
    command: [
      "mongod",
      "--replSet", "dkaReplicaSet",
      "--keyFile", "/data/configdb/keyfile",
      "--port",
      "27019",
      "--bind_ip_all"
    ]

networks:
  mongo-net:
    driver: bridge
    ipam:
      config:
        - subnet: 103.113.1.0/24

volumes:
  mongodb1_data:
    driver: local
  mongodb2_data:
    driver: local
  mongodb3_data:
    driver: local
